### ISSUE TITLE
Question: Is `cargo test` covered by Rust Analyzer?

### ISSUE THREAD

**Issue by TieWay59** [panicbit/vscode-cargo#15]
![image](https://github.com/panicbit/vscode-cargo/assets/40034603/51233999-2e02-4df5-bd61-edf30b709037)

![image](https://github.com/panicbit/vscode-cargo/assets/40034603/d305ef2e-103f-48a0-8ffb-c1b6fad4abcf)

Though this is not very well integrated with cargo for now. @panicbit  what's your ideas about this feature? will you still have a plan working on this feature?

**Comment by panicbit** [comment]
`rust-analyzer` has fairly good test integration as far as I know, but `vscode-cargo` does not and probably will not in the future.
