### ISSUE TITLE
Newest version match is done incorrectly

### ISSUE THREAD

**Issue by mtnmts** [panicbit/vscode-cargo#5]
The current implementation decides the package "0.9.9" is larger than "0.14.2" because the comparison is done digit by digit.

**Comment by panicbit** [comment]
Hey, sorry for responding to this so late!
It looks like you are talking about the "cargo add" command?
If so, this is/was an issue with [cargo-edit](https://github.com/killercup/cargo-edit).

**Comment by mtnmts** [comment]
Ok, sorry about that! I'm closing this, I'll try and check later if it still exists in the upstream.

Also apologize for my late reply.
