### ISSUE TITLE
Extension raises compiler errors multiple times

### ISSUE THREAD

**Issue by EthanZeigler** [panicbit/vscode-cargo#6]
It's hard to exactly describe what's going on, but I think this says enough. Took me forever to find the offending extension.

<img width="1392" alt="Screen Shot 2020-01-04 at 9 49 34 PM" src="https://user-images.githubusercontent.com/9123320/71774414-3a3f6d80-2f3c-11ea-82e3-e275323b7714.png">

**Comment by panicbit** [comment]
Thanks, I'll look into it.
In the meantime, if you want to, you can disable the cargo check function in the settings and use the Rust/rls addon instead.

**Comment by panicbit** [comment]
This should be fixed now in `0.2.1`.
If you still see duplicates after this, then they probably come from a different add-on.
